# replace the title with the name of your restaurant!
title: "Bistro Baguette"
# write your restaurateur alter ego name below, or your own name
author: Mm. Dubois
# write your Google Analytics tracking ID below
google_analytics: G-5W0WCL0XT4

theme: minima

collections:
  explorations:
    output: true
