# TODO: replace the title with the name of your restaurant!
title: "Data Exploration Blog"
# TODO: write your restaurateur alter ego name below, or your own name
author: 
# TODO: write your Google Analytics tracking ID below
google_analytics: G-5W0WCL0XT4

theme: minima

collections:
  explorations:
    output: true
